### ISSUE TITLE
Thanks for the project.

### ISSUE THREAD

**Issue by edwin-oetelaar** [JSchaenzle/ESP32-NeoPixel-WS2812-RMT#5]
Hello Jordan,

I grabbed the code and put it in my project. It works fine (on 1 LED).
I will be hacking it up a bit, I will change the hardcoded pin-numbers into runtime parameters.
Your solution using the RMT was the most elegant one I found for controlling the WS2812 devices, no assembly or dependencies. Very good.

The best wishes from The Netherlands,
Edwin 

After some time I found a serious bug in the code : reference to uninitialized data. Not so good! 
Here is the fix (ws2812_control.c about line 24)
```
void ws2812_control_init(void)
{
    rmt_config_t config = {
        .rmt_mode = RMT_MODE_TX,
        .channel = LED_RMT_TX_CHANNEL,
        .gpio_num = LED_RMT_TX_GPIO,
        .mem_block_num = 3,
        .tx_config.loop_en = false,
        .tx_config.carrier_en = false,
        .tx_config.idle_output_en = true,
        .tx_config.idle_level = RMT_IDLE_LEVEL_LOW,
        .clk_div = 2,
    };

```

**Comment by JSchaenzle** [comment]
Fixed here: https://github.com/JSchaenzle/ESP32-NeoPixel-WS2812-RMT/pull/12
