### ISSUE TITLE
bug : partly uninitialized struct used, random errors, use RAII

### ISSUE THREAD

**Issue by edwin-oetelaar** [JSchaenzle/ESP32-NeoPixel-WS2812-RMT#6]
https://github.com/JSchaenzle/ESP32-NeoPixel-WS2812-RMT/blob/31ac15d3bc667dc8e91f63c55a36063ccbb1cc91/ws2812_control.c#L24

is created on the stack but only some values of the memory are filled in.
This leads to the .flag part not being 0x00 when it should be, (it thinks RMT_CHANNEL_FLAGS_ALWAYS_ON) which leads to using the wrong clock source (1 MHz ref instead of RMT_BASECLK_APB)

The solution is simple, RAII : Resource Acquisition Is Initialization.

Just do it like this : 
```
rmt_config_t config = {0,};
```

or even better:
```
rmt_config_t config = {
        .rmt_mode = RMT_MODE_TX,
        .channel = LED_RMT_TX_CHANNEL,
        .gpio_num = LED_RMT_TX_GPIO,
        .mem_block_num = 3,
        .tx_config.loop_en = false,
        .tx_config.carrier_en = false,
        .tx_config.idle_output_en = true,
        .tx_config.idle_level = RMT_IDLE_LEVEL_LOW,
        .clk_div = 2,
    };
```

**Comment by JSchaenzle** [comment]
Fixed here: https://github.com/JSchaenzle/ESP32-NeoPixel-WS2812-RMT/pull/12
